### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by SOOSOO37** [SOOSOO37/Todorepository#9]
### Todo App 기능
1.할일 생성 기능
2.할일 수정 기능
3.할일 삭제 기능
4.할일 조회 기능
5.할일 완료 기능

### 해당 기능을 구현하기위해 할 일
1. [ ]  할일 생성 기능 구현
2. [ ]  할일 수정 기능 구현
3. [ ]  할일 삭제 기능 구현
4. [ ] 할일 조회기능 구현
5. [ ] 할일 완료 처리 구현

### 예상 작업 시간
6h
